spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_OAUTH_CLIENT_ID}
            clientSecret: ${GOOGLE_OAUTH_CLIENT_SECRET}


  datasource:
    hikari:
      maxLifeTime: 600000
    url: ${DATABASE_HOSTNAME} 
    driver-class-name: org.postgresql.Driver
    initialSize: 5
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    removeAbandoned: true
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: false
